### ISSUE TITLE
[Bug] dbtCore - after upgrading, can't run DBT

### ISSUE THREAD

**Issue by moseleyi** [dbt-labs/dbt-core#10135]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I installed dbt-core, bigquery, and postgres, and then when typing `dbt --version` I get this error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\___\AppData\Roaming\Python\Python312\Scripts\dbt.exe\__main__.py", line 4, in <module>
  File "C:\Users\___t\AppData\Roaming\Python\Python312\site-packages\dbt\cli\__init__.py", line 1, in <module>
    from .main import cli as dbt_cli  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\___\AppData\Roaming\Python\Python312\site-packages\dbt\cli\main.py", line 14, in <module>
    from dbt.cli import requires, params as p
  File "C:\Users\___\AppData\Roaming\Python\Python312\site-packages\dbt\cli\requires.py", line 10, in <module>
    from dbt.adapters.factory import adapter_management, register_adapter, get_adapter
ModuleNotFoundError: No module named 'dbt.adapters.factory'
```

This is after installing bigquery, postgres, 

### Expected Behavior

Should show the version of dbt packages

### Steps To Reproduce

1. Install dbt-core
2. Run `dbt --version`

### Environment

```markdown
- OS: Windows
- Python: 3.12
- dbt: 1.8
```

**Comment by jtcohen6** [comment]
@moseleyi Could you run `pip freeze | grep 'dbt'` and report back with the exact versions of Python packages that you have installed?

Also - you might try installing all of these by name, along with the `--upgrade` flag, and see if that resolves the issue for you:
```
pip install --upgrade dbt-core dbt-bigquery dbt-postgres
```

**Comment by rubenhelsloot** [comment]
@jtcohen6 I have the same issue, this is the output you asked for:

```
❯ pip freeze | grep 'dbt'
dbt-adapters==1.1.1
dbt-common==1.0.4
dbt-core==1.8.0
dbt-extractor==0.5.1
dbt-postgres==1.8.0
dbt-semantic-interfaces==0.5.1
sqlfluff-templater-dbt==3.0.6
```

The issue persists when I uninstall and then reinstall `dbt-core` and `dbt-postgres`. FWIW I'm using poetry.

**Comment by jtcohen6** [comment]
Thanks @rubenhelsloot! Are you also using Python 3.12?

**Comment by moseleyi** [comment]
My output:

```
dbt-adapters==1.1.1
dbt-common==1.0.4
dbt-core==1.8.0
dbt-extractor==0.5.1
dbt-postgres==1.8.0
dbt-semantic-interfaces==0.5.1
```

Some people in my team got it working but maybe because it was clean install, they never had to use python packages before. Perhaps some dependencies of dbt are not updated with the latest update?

**Comment by moseleyi** [comment]
Surprisingly dbt 1.7.13 works fine with Python 3.12.3 - I checked on my other laptop

**Comment by dbeatty10** [comment]
@rubenhelsloot! Are you also using Windows?

@moseleyi Which commands are you using to installing dbt? Are you using a virtual environment with `venv` or Poetry?

The following files and commands worked for me:
- on macOS
- using `venv`
- with Python 3.12.3 (managed by `pyenv`)

Create this file:

`requirements.txt`

```
dbt-adapters==1.1.1
dbt-common==1.0.4
dbt-core==1.8.0
dbt-extractor==0.5.1
dbt-postgres==1.8.0
dbt-semantic-interfaces==0.5.1
```

Run these commands:

```shell
python3 -m venv env
source env/bin/activate
python -m pip install --upgrade pip
python -m pip install -r requirements.txt
source env/bin/activate
python --version
dbt --version
deactivate
```

Output:

```
Python 3.12.3
Core:
  - installed: 1.8.0
  - latest:    1.8.0 - Up to date!

Plugins:
  - postgres: 1.8.0 - Up to date!
```

**Comment by leoebfolsom** [comment]
I had the same issue on Python 3.9.6, and it was resolved on upgrade to 3.12.

**Comment by moseleyi** [comment]
I don't use venv nor poetry. At first I just upgraded `pip install dbt-core --upgrade` and the adapters. That didn't work so I tried uninstalling everything and installing again using different commands (core + adapters in one command, adapter only etc.)

All of them produce this error

**Comment by troyharvey** [comment]
Reproduced with Python 3.10.

```
＄ python --version
Python 3.10.14

＄ dbt deps
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ds-redshift/bin/dbt", line 5, in <module>
    from dbt.cli.main import cli
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ds-redshift/lib/python3.10/site-packages/dbt/cli/__init__.py", line 1, in <module>
    from .main import cli as dbt_cli  # noqa
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ds-redshift/lib/python3.10/site-packages/dbt/cli/main.py", line 14, in <module>
    from dbt.cli import requires, params as p
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ds-redshift/lib/python3.10/site-packages/dbt/cli/requires.py", line 10, in <module>
    from dbt.adapters.factory import adapter_management, register_adapter, get_adapter
ModuleNotFoundError: No module named 'dbt.adapters.factory'
```

**Comment by augusthorlen0** [comment]
@moseleyi I ran into the exact same problem. My issue was that I had named a folder `dbt` where Python tried to import `adapters` from the folder rather than the package. I renamed the folder to something different and it worked again as expected.

Might be worth checking

**Comment by paulbakkerbloom** [comment]
Had the same issue with Python 3.9.18 -> solved when I upgraded to Python 3.11.6

I use poetry and upgraded through `poetry update`

```
dbt-adapters                          1.1.1             The set of adapter ...
dbt-bigquery                          1.8.0             The Bigquery adapte...
dbt-common                            1.0.4             The shared common u...
dbt-core                              1.8.0             With dbt, data anal...
dbt-extractor                         0.5.1             A tool to analyze a...
dbt-semantic-interfaces               0.5.1             The shared semantic...
dbt-tests-adapter                     1.8.0             The set of reusable...
```

**Comment by moseleyi** [comment]
I was hoping it was about python issue but seems like it's not. It could be a dependency that should be updated with dbt core update but isn't being forced to update?

**Comment by moseleyi** [comment]
I also found this: https://github.com/AltimateAI/vscode-dbt-power-user/issues/1029  but we all have `dbt-adapters` installed

**Comment by dbeatty10** [comment]
Thanks for this info @brabster 🏅

Could you share the contents of your `requirements.txt` file also?

**Comment by brabster** [comment]
@dbeatty10
It's just the dbt-bigquery dependency. Originally as per repo. https://github.com/brabster/pypi_vulnerabilities/blob/main/requirements.txt

Clean venv, set to dbt-bigquery==1.7.7 to force pre-1.8.0 and install.  Works. 
Then set to dbt-bigquery>=1.7.7 to upgrade to latest. Broken
Clean venv, install same requirements. Works

**Comment by jtcohen6** [comment]
@brabster If in step (2), you run `pip install --upgrade dbt-core dbt-common dbt-adapters dbt-bigquery`, do you still see the error?

(I'm hoping this _might_ be because the underlying dependencies are not being upgraded, when they should be, but I'm not 100% positive: https://github.com/dbt-labs/dbt-core/pull/10123)

**Comment by dbeatty10** [comment]
Thank you @brabster ! 🏅 I was able to reproduce the error using your description. See "reprex" below for full details.

@jtcohen6 when I tried running `pip install --upgrade dbt-core dbt-common dbt-adapters dbt-bigquery`, it still gave the same error.


<details>

<summary>

### Reprex
</summary>

Create requirements files for both 1.7 and 1.8:

```shell
cat << EOF > requirements_1.7.txt
dbt-bigquery==1.7.7
EOF
cat << EOF > requirements_1.8.txt
dbt-adapters==1.1.1
dbt-common==1.0.4
dbt-core==1.8.0
dbt-extractor==0.5.1
dbt-bigquery==1.8.0
dbt-semantic-interfaces==0.5.1
EOF
```

✅ Create a fresh virtual environment and install the requirements for 1.7:

```shell
rm -rf env
python3 -m venv env
source env/bin/activate
python -m pip install -r requirements_1.7.txt
source env/bin/activate
dbt --version
```

❌ Try upgrading by installing the requirements for 1.8 in the same virtual environment:

```shell
python -m pip install -r requirements_1.8.txt
source env/bin/activate
dbt --version
```

Get an error like the following:

```
    from dbt.adapters.factory import adapter_management, register_adapter, get_adapter
ModuleNotFoundError: No module named 'dbt.adapters.factory'
```

✅ Try upgrading by installing the requirements for 1.8 in a fresh virtual environment:

```shell
deactivate
rm -rf env
python3 -m venv env
source env/bin/activate
python -m pip install -r requirements_1.8.txt
source env/bin/activate
dbt --version
```

</details>

**Comment by dbeatty10** [comment]
When I got the same error as the reported above, the following workaround resolved it for me:

```shell
python -m pip uninstall -y dbt-adapters
python -m pip install --upgrade dbt-core dbt-common dbt-adapters
dbt --version
```

**Comment by moseleyi** [comment]
Yes, this workaround seems to work. But what is the underlying issue?

**Comment by brabster** [comment]
Seems to be related to the move of dbt-adapters from part of dbt-core to standalone. I can upgrade no problem from a 1.8 pre-release to latest, but anything from before dbt-adapters being standalone and boom.

I can see in verbose pip install logs that it's going around deleting the files in dbt/adapters/... but no evidence that it knows to replace them. Weird. I wonder if it's something to do with going to a standalone dependency but having all the files end up in the same place, maybe a kind of race condition so they are already there when it's checking what to install, but then it goes and deletes them afterwards. Perhaps moving the standalone adapters directory tree away from where it used to be could resolve the problem? Not had chance to check

**Comment by dbeatty10** [comment]
@moseleyi I don't know the underlying root cause.

But I'm able to see some differences when I create two different virtual environments:
- `env1` is the environment that has the error
- `env2` is the environment that is working as expected

### Difference 1

One of the differences is in this file: `lib/python3.12/site-packages/dbt/__init__.py`
- `env1` has contents that are identical to [dbt-postgres `dbt/__init__.py`](https://github.com/dbt-labs/dbt-postgres/blob/e23d0a7bb7d4a32598778922ce28578ad4be0e77/dbt/__init__.py)
- `env2` has contents that are identical to [dbt-adapters `dbt/__init__.py`](https://github.com/dbt-labs/dbt-adapters/blob/eda109542efd1703fd08e242006ae4d3fc476b38/dbt/__init__.py)
- Neither environment has contents identical to [dbt-core `core/dbt/__init__.py`](https://github.com/dbt-labs/dbt-core/blob/32a7f82772d90a4b9ab443908f5f4455d0aa2c73/core/dbt/__init__.py)


### Difference 2

`env2` has the following files/folders within `lib/python3.12/site-packages/dbt/adapters` that are not in `env1`:

- `__init__.py`
- `cache.py`
- `capability.py`
- `factory.py`
- `protocol.py`
- `reference_keys.py`
- `sql`

<details>
<summary>
These are the files/folders that are within both:
</summary>

- `__about__.py`
- `__pycache__`
- `base`
- `clients`
- `contracts`
- `events`
- `exceptions`
- `postgres`
- `py.typed`
- `relation_configs`
- `utils.py`
</details>

**Comment by dbeatty10** [comment]
Here's another command that resolved the error for me:

```shell
python -m pip install --force-reinstall dbt-adapters
```

**Comment by brabster** [comment]
For info `pip install -U --force-reinstall -r requirements.txt` does not work, unfortunately.

**Comment by brabster** [comment]
Following previous comments - I think it might be a bug in pip? Seems like the last thing pip does is uninstall the old versions including the old dbt-core, which used to contain the adapters directory. If it's deleting the common files when it does that uninstall, that might explain the missing files when you try to upgrade from core to standalone adapters

```
Installing collected packages: daff, dbt-semantic-interfaces, dbt-common, dbt-adapters, dbt-core, dbt-bigquery
  Attempting uninstall: dbt-semantic-interfaces
    Found existing installation: dbt-semantic-interfaces 0.4.4
    Uninstalling dbt-semantic-interfaces-0.4.4:
      Successfully uninstalled dbt-semantic-interfaces-0.4.4
  Attempting uninstall: dbt-core
    Found existing installation: dbt-core 1.7.14
    Uninstalling dbt-core-1.7.14:
      Successfully uninstalled dbt-core-1.7.14
  Attempting uninstall: dbt-bigquery
    Found existing installation: dbt-bigquery 1.7.7
    Uninstalling dbt-bigquery-1.7.7:
      Successfully uninstalled dbt-bigquery-1.7.7
Successfully installed daff-1.3.46 dbt-adapters-1.1.1 dbt-bigquery-1.8.1 dbt-common-1.0.4 dbt-core-1.8.0 dbt-semantic-interfaces-0.5.1
```

**Comment by jkleinkauff** [comment]
Same problem here. @dbeatty10 's solution worked for me.
```
python -m pip uninstall -y dbt-adapters
python -m pip install --upgrade dbt-core dbt-common dbt-adapters
dbt --version
```

**Comment by brabster** [comment]
I had a look around in the pip source code and if I'm understanding this correctly, it's clear what the problem is and any upgrade from pre-standalone adapters to standalone adapters will break in this way.

After interrogating PyPI for the latest versions of things, we get this (verbose) log line like this:

`Installing collected packages: daff, dbt-semantic-interfaces, dbt-common, dbt-adapters, dbt-core, dbt-bigquery`

That's from line 54 [here](https://github.com/pypa/pip/blob/612515d2e0a6ff8676c139c096a45bc28b3456f4/src/pip/_internal/req/__init__.py#L54) which enumerates to_install - an OrderedDict, so the packages are always in alpha order, and `dbt-adapters` comes before `dbt-core` (demonstrated in the debug line I showed).

Now on [line 61](https://github.com/pypa/pip/blob/612515d2e0a6ff8676c139c096a45bc28b3456f4/src/pip/_internal/req/__init__.py#L61), pip loops over that ordered list, i.e. `dbt-adapters` first and then `dbt-core`, and for each package **uninstalls** the previous version and installs the new version.

Because `dbt-core` follows `dbt-adapters`, the files they have in common get deleted as part of the dbt-core uninstall and leaves a broken installation.

It's certainly possible I'm wrong, but I attach a verbose upgrade log and you can see the ordering and uninstall activity happening in a manner consistent with this explanation towards the end.

[pip.log](https://github.com/dbt-labs/dbt-core/files/15357036/pip.log)

It also explains every reported behaviour in this issue:
- any attempt to update dbt-core in place with an existing version of dbt-core that included the adapter file structure will cause this break
- cleaning the venv first will avoid the reinstall behaviour and be successful
- `--force-reinstall` flag will make pip copy dbt-adapters back into place, fixing the problem

If I can find an old version of dbt-core that didn't have those adapters files in that specific location, then I think an upgrade should work, if my theory is correct. Will let you know if I can verify that.

**Comment by naveenwashere** [comment]
> ```shell
> pip install --force-reinstall dbt-adapters
> ```

This worked for me. Thanks @dbeatty10 .

**Comment by karenderer** [comment]
I found a way to upgrade to 1.8 with poetry by downgrading dbt-adapters to 1.1.0 and then updating it to 1.1.1 but it's not ideal.

<details><summary>Details</summary>
<p>

$ poetry add --group dev dbt-core=^1.8.1 dbt-snowflake=^1.8.2
$ dbt --version

> `ModuleNotFoundError: No module named 'dbt.adapters.factory'`

$ poetry add --group dev dbt-adapters = "^1.1.0"

change the following in pyproject.toml
* set dbt-adapters to 1.1.0
* set dbt-core to 1.8.0
* set dbt-snowflake to 1.8.0

$ poetry lock --no-update
$ poetry install --sync --no-root

$ dbt version

> works

$ dbt debug

> `TypeError: __post_serialize__() got an unexpected keyword argument 'context'`

change the following in pyproject.toml
* set dbt-adapters to 1.1.1

$ poetry lock --no-update
$ poetry install --sync --no-root

$ dbt version

> works

$ dbt debug 

> runs successfully


</p>
</details>

**Comment by MikeMccree** [comment]
> > ```shell
> > pip install --force-reinstall dbt-adapters
> > ```
> 
> This worked for me. Thanks @dbeatty10 .

+1 worked for me as well. 

I am on mac, ran the following:
`
pip install --upgrade \
  dbt-core \
  dbt-postgres \
  dbt-redshift \
  dbt-spark\
  dbt-athena-community\
  dbt-glue
`

Encountered the error with adapters. ran the `force-reinstall` and we all good.. Thanks @dbeatty10

**Comment by rizahmeds** [comment]
Upgraded python version from 3.11.5 to 3.12.3, and it worked.

**Comment by dun-x** [comment]
> Here's another command that resolved the error for me:
> 
> ```shell
> python -m pip install --force-reinstall dbt-adapters
> ```

This work for me

**Comment by elyobo** [comment]
For those using `poetry`, my fix was to remove the env and reinstall, e.g.

```sh
poetry env remove 3.12
poetry install
```

**Comment by Evelyn-yx-Li** [comment]
Hi team, is there any plan to resolve the issue without entering `pip install --force-reinstall dbt-adapters`? 
Because we're currently using `pip install` within the GitHub Action. Just wondering if we need to add the commands within the workflow files.
Thank you!

**Comment by dbeatty10** [comment]
@Evelyn-yx-Li We're not aware of anything we can do about this that wouldn't risk breaking other things. So if you're getting this error in your GitHub Actions, then we'd recommend adding a workaround to handle it.

**Comment by elyobo** [comment]
@Evelyn-yx-Li it seems that this is explicitly an _upgrading_ problem, so possibly it's related to caching dependency installs e.g. if you're doing so via [`actions/setup-python`](https://github.com/actions/setup-python?tab=readme-ov-file#caching-packages-dependencies); maybe try disabling if so?

That said, we're caching `poetry` dependencies in that way and haven't run into issues, it was just local developer installs that seemed to have problems.

**Comment by brabster** [comment]
@elyobo confident this is the underlying reason https://github.com/dbt-labs/dbt-core/issues/10135#issuecomment-2118230255. If so it is explicitly an upgrading problem, because of the order in which packages are cleaned up and dbt's placing multiple modules into a shared directory structure. Explains the variety of issues reported.

**Comment by Evelyn-yx-Li** [comment]
Hi, I've tried the solutions above in our prod, but it shows "command not found". Both force-reinstall and uninstall dbt-adapters. But it works well within local and CI.
```sh
------------------------------------------------------------------------------------------------------------------------
DBT VERSION
------------------------------------------------------------------------------------------------------------------------
Checking DBT version...
dbt -v
./dbt-forklift.sh: line 49: dbt: command not found

------------------------------------------------------------------------------------------------------------------------
SET UP DBT
------------------------------------------------------------------------------------------------------------------------
Installing DBT dependencies...
pip uninstall -y dbt-adapters
WARNING: Skipping dbt-adapters as it is not installed.
pyenv: cannot rehash: /usr/local/.pyenv/shims isn't writable
pip install dbt-core dbt-bigquery==1.8.1 dbt-redshift==1.8.0 dbt-snowflake==1.8.3
Defaulting to user installation because normal site-packages is not writeable
Collecting dbt-core
  Using cached dbt_core-1.8.2-py3-none-any.whl.metadata (3.9 kB)
Collecting dbt-bigquery==1.8.1
  Using cached dbt_bigquery-1.8.1-py3-none-any.whl.metadata (3.2 kB)
Collecting dbt-redshift==1.8.0
  Using cached dbt_redshift-1.8.0-py3-none-any.whl.metadata (3.2 kB)
Collecting dbt-snowflake==1.8.3
  Using cached dbt_snowflake-1.8.3-py3-none-any.whl.metadata (3.2 kB)
Collecting dbt-common<2.0,>=1.0.4 (from dbt-bigquery==1.8.1)
  Using cached dbt_common-1.3.0-py3-none-any.whl.metadata (5.3 kB)
Collecting dbt-adapters<2.0,>=1.1.1 (from dbt-bigquery==1.8.1)
  Using cached dbt_adapters-1.2.1-py3-none-any.whl.metadata (2.5 kB)
Collecting google-cloud-bigquery<4.0,>=3.0 (from google-cloud-bigquery[pandas]<4.0,>=3.0->dbt-bigquery==1.8.1)
  Using cached google_cloud_bigquery-3.24.0-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting google-cloud-storage~=2.4 (from dbt-bigquery==1.8.1)
  Using cached google_cloud_storage-2.17.0-py2.py3-none-any.whl.metadata (6.6 kB)
Collecting google-cloud-dataproc~=5.0 (from dbt-bigquery==1.8.1)
  Using cached google_cloud_dataproc-5.9.3-py2.py3-none-any.whl.metadata (5.2 kB)
Collecting google-api-core>=2.11.0 (from dbt-bigquery==1.8.1)
  Using cached google_api_core-2.19.0-py3-none-any.whl.metadata (2.7 kB)
Collecting dbt-postgres~=1.8.0 (from dbt-redshift==1.8.0)
  Using cached dbt_postgres-1.8.1-py3-none-any.whl.metadata (3.4 kB)
Collecting redshift-connector!=2.0.914,<2.0.918,>=2.0.913 (from dbt-redshift==1.8.0)
  Using cached redshift_connector-2.0.917-py3-none-any.whl.metadata (66 kB)
Collecting sqlparse<0.6.0,>=0.5.0 (from dbt-redshift==1.8.0)
  Using cached sqlparse-0.5.0-py3-none-any.whl.metadata (3.9 kB)
Collecting agate (from dbt-redshift==1.8.0)
  Using cached agate-1.11.0-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting snowflake-connector-python~=3.0 (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake==1.8.3)
  Using cached snowflake_connector_python-3.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting agate (from dbt-redshift==1.8.0)
  Using cached agate-1.9.1-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting Jinja2<4,>=3.1.3 (from dbt-core)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting mashumaro<4.0,>=3.9 (from mashumaro[msgpack]<4.0,>=3.9->dbt-core)
  Using cached mashumaro-3.13-py3-none-any.whl.metadata (114 kB)
Collecting logbook<1.6,>=1.5 (from dbt-core)
  Using cached Logbook-1.5.3.tar.gz (85 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting click<9.0,>=8.0.2 (from dbt-core)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting networkx<4.0,>=2.3 (from dbt-core)
  Using cached networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
Collecting protobuf<5,>=4.0.0 (from dbt-core)
  Using cached protobuf-4.25.3-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
Collecting requests<3.0.0 (from dbt-core)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting pathspec<0.13,>=0.9 (from dbt-core)
  Using cached pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
Collecting dbt-extractor<=0.6,>=0.5.0 (from dbt-core)
  Using cached dbt_extractor-0.5.1-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Collecting minimal-snowplow-tracker<0.1,>=0.0.2 (from dbt-core)
  Using cached minimal-snowplow-tracker-0.0.2.tar.gz (12 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting dbt-semantic-interfaces<0.6,>=0.5.1 (from dbt-core)
  Using cached dbt_semantic_interfaces-0.5.1-py3-none-any.whl.metadata (2.6 kB)
Collecting packaging>20.9 (from dbt-core)
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting pytz>=2015.7 (from dbt-core)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting pyyaml>=6.0 (from dbt-core)
  Using cached PyYAML-6.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting daff>=1.3.46 (from dbt-core)
  Using cached daff-1.3.46.tar.gz (149 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting typing-extensions>=4.4 (from dbt-core)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting Babel>=2.0 (from agate->dbt-redshift==1.8.0)
  Using cached Babel-2.15.0-py3-none-any.whl.metadata (1.5 kB)
Collecting isodate>=0.5.4 (from agate->dbt-redshift==1.8.0)
  Using cached isodate-0.6.1-py2.py3-none-any.whl.metadata (9.6 kB)
Collecting leather>=0.3.2 (from agate->dbt-redshift==1.8.0)
  Using cached leather-0.4.0-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting parsedatetime!=2.5,>=2.1 (from agate->dbt-redshift==1.8.0)
  Using cached parsedatetime-2.6-py3-none-any.whl.metadata (4.7 kB)
Collecting python-slugify>=1.2.1 (from agate->dbt-redshift==1.8.0)
  Using cached python_slugify-8.0.4-py2.py3-none-any.whl.metadata (8.5 kB)
Collecting pytimeparse>=1.1.5 (from agate->dbt-redshift==1.8.0)
  Using cached pytimeparse-1.1.8-py2.py3-none-any.whl.metadata (3.4 kB)
Collecting colorama<0.5,>=0.3.9 (from dbt-common<2.0,>=1.0.4->dbt-bigquery==1.8.1)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting jsonschema<5.0,>=4.0 (from dbt-common<2.0,>=1.0.4->dbt-bigquery==1.8.1)
  Using cached jsonschema-4.22.0-py3-none-any.whl.metadata (8.2 kB)
Collecting python-dateutil<3.0,>=2.0 (from dbt-common<2.0,>=1.0.4->dbt-bigquery==1.8.1)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting psycopg2<3.0,>=2.9 (from dbt-postgres~=1.8.0->dbt-redshift==1.8.0)
  Using cached psycopg2-2.9.9.tar.gz (384 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  Ã Getting requirements to build wheel did not run successfully.
  â exit code: 1
  â°â> [21 lines of output]
      running egg_info
      writing psycopg2.egg-info/PKG-INFO
      writing dependency_links to psycopg2.egg-info/dependency_links.txt
      writing top-level names to psycopg2.egg-info/top_level.txt
      
      Error: pg_config executable not found.
      
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
      
          python setup.py build_ext --pg-config /path/to/pg_config build ...
      
      or with the pg_config option in 'setup.cfg'.
      
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Ã Getting requirements to build wheel did not run successfully.
â exit code: 1
â°â> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
dbt -v
./dbt-forklift.sh: line 61: dbt: command not found
./dbt-forklift.sh: line 62: dbt: command not found

```

**Comment by davidwitk** [comment]
@dbeatty10 Do you know if this only relevant for upgrading to 1.8? Or is this going to affect future versions, too? Context: I wonder if I should add the workaround as general recommendation for upgrading dbt

**Comment by ann8ty** [comment]
I also have this issue on upgrade. 

python --version
Python 3.11.9
I use venv with vs code

 dbt --version
Traceback (most recent call last):
  File "/Users/ann/code/data/data-workflows/.venv/bin/dbt", line 5, in <module>
    from dbt.cli.main import cli
  File "/Users/ann/code/data/data-workflows/.venv/lib/python3.11/site-packages/dbt/cli/__init__.py", line 1, in <module>
    from .main import cli as dbt_cli  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ann/code/data/data-workflows/.venv/lib/python3.11/site-packages/dbt/cli/main.py", line 14, in <module>
    from dbt.cli import requires, params as p
  File "/Users/ann/code/data/data-workflows/.venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 10, in <module>
    from dbt.adapters.factory import adapter_management, register_adapter, get_adapter
ModuleNotFoundError: No module named 'dbt.adapters.factory'

pip freeze | grep 'dbt'
airflow-dbt-python==2.0.1
dbt-adapters==1.3.2
dbt-common==1.5.0
dbt-core==1.8.3
dbt-extractor==0.5.1
dbt-postgres==1.7.17
dbt-redshift==1.7.7
dbt-semantic-interfaces==0.5.1
dbt-tests-adapter==1.9.1

pip install --force-reinstall dbt-adapters

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dbt-postgres 1.7.17 requires dbt-core==1.7.17, but you have dbt-core 1.8.3 which is incompatible.
dbt-redshift 1.7.7 requires dbt-core~=1.7.0, but you have dbt-core 1.8.3 which is incompatible.

my req file
airflow-dbt-python==2.0.1 # latest Jul 2024
dbt-core==1.7.17 # airflow-dbt-python 2.0.1 depends on dbt-core<1.8.0 and >=1.4.0; python_version >= "3.11"
dbt-redshift==1.7.7

my test req file
dbt-tests-adapter

but dbt works (But wrong version)

dbt --version                             
Core:
  - installed: 1.8.3
  - latest:    1.8.3 - Up to date!

Plugins:

was concerned that dbt had moved from 1.7.17 to 1.8.3 when it was pinned, changed my dbt tests file

dbt-tests-adapter==1.7.17


pip freeze | grep 'dbt'
airflow-dbt-python==2.0.1
dbt-adapters==1.3.2
dbt-common==1.5.0
dbt-core==1.7.17
dbt-extractor==0.5.1
dbt-postgres==1.7.17
dbt-redshift==1.7.7
dbt-semantic-interfaces==0.4.4
dbt-tests-adapter==1.7.17


 dbt --version
Core:
  - installed: 1.7.17
  - latest:    1.8.3  - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - redshift: 1.7.7  - Update available!
  - postgres: 1.7.17 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

**Comment by dbeatty10** [comment]
> @dbeatty10 Do you know if this only relevant for upgrading to 1.8? Or is this going to affect future versions, too? Context: I wonder if I should add the workaround as general recommendation for upgrading dbt

@davidwitk I'm assuming this will apply anytime upgrading dbt <1.8.0 to dbt >= 1.8.0.

**Comment by dbeatty10** [comment]
@ann8ty I'd recommend trying the commands in https://github.com/dbt-labs/dbt-core/issues/10135#issuecomment-2113728550.

**Comment by brabster** [comment]
Can you run 1.7.x adapter implementations with dbt 1.8.x core/adapters? If not then that might explain @ann8ty problem, looks like they have pinned exact 1.7.17 Pg/Redshift adapter versions.

More general question maybe aimed at @dbeatty10 - If you folks are decoupling versions of adapter implementations from core and adapters packages, how can a user tell whether different versions are compatible? Probably some docs somewhere I haven't found?

**Comment by jessanmen1** [comment]
`pip install -r requirements.txt --no-cache-dir --ignore-installed` worked for me on Python 3.10.

**Comment by mroy-seedbox** [comment]
Simply upgrading `dbt-adapters` solved the issue! 👌

**Comment by paulav6** [comment]
Re-installing  `dbt-adapters ` did not work for me. However cleaning up virtual environment  `rm -rf .ve` and reinstalling `pip install --upgrade -r requirements.txt` that had the dbt versions worked.

**Comment by nguyentoanit** [comment]
After trying all above solutions, Only upgrading python to v3.12 worked for me. 🤷 
```
- OS: Linux
- Python: 3.12.4
- dbt: 1.8.4
```

**Comment by ozkary** [comment]
After upgrading to dbt 1.8.4, I also got the error:    

```
File "/home/ozkary/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 10, in <module>
    from dbt.adapters.factory import adapter_management, register_adapter, get_adapter
ModuleNotFoundError: No module named 'dbt.adapters.factory'
```

I was able to correct this by removing the current adapters and installing it again:

```
pip uninstall -y dbt-adapters

pip install --upgrade dbt-adapters

```

All looks fine now.  I am using python `3.8.10`

```
Core:
  - installed: 1.8.4
  - latest:    1.8.4 - Up to date!

Plugins:
  - bigquery: 1.8.2 - Up to date!
```

Thanks for helping us resolve this.

**Comment by moltar** [comment]
I have some observations to throw in.

It appears that the problem is very intermittent. I've had the same CI run fail, and then after retrying it had passed.

I used a `pip freeze` solution, and no force ugprades.

On the same GitHub Actions run, I had three workflows that used dbt install steps that were identical. One out of three runs had failed with the "No module named 'dbt.adapters.factory'" error.

Then, I clicked "Re-run failed" and it passed.

```
$> grep dbt "$DBT_PROJECT_DIR/requirements.txt"

dbt-adapters==1.4.0
dbt-common==1.7.0
dbt-core==1.8.4
dbt-extractor==0.5.1
dbt-postgres==1.8.2
dbt-semantic-interfaces==0.5.1
sqlfluff-templater-dbt==3.1.0
```

**Comment by brabster** [comment]
@moltar are you caching the dependencies in the GH Action? I would suspect that for causing intermittent problems as the state of what's ending up on in the filesystem (and then being cached) may be quite unpredictable. If you are caching, maybe try disabling that to get a clean install from scratch?

**Comment by moltar** [comment]
@brabster Yup:

```yaml
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          cache: pip
          python-version: '3.12'
```

**Comment by moltar** [comment]
@brabster Removed caching, but still get random failures.

**Comment by brabster** [comment]
@moltar strange - if the root cause I identified earlier is true, clean install should not have a problem (unless something else is going on as well to confound the problem). Curious, so happy to take a look if you can share the details of the workflow between the setup python task the step that fails like what's the specific install command, and any logs you can share about the install/update process?

**Comment by alxsbn** [comment]
Same issue after upgrading dbt within our Airflow stack. We have Python `3.8.18`. We try to solve this by using `pip install --upgrade dbt-adapters` without success as-well-as doing a --force-recreate of our stack (so it's not a cache issue)
```
airflow-dbt==0.4.0
dbt-adapters==1.4.1
dbt-common==1.7.0
dbt-core==1.8.6
dbt-databricks==1.8.5
dbt-extractor==0.5.1
dbt-semantic-interfaces==0.5.1
dbt-spark==1.8.0
```

**Comment by saeedkhattak** [comment]
Had this issue with my dbt with oracle adapter. The following code fixed it: 
`pip` install --upgrade dbt-core dbt-oracle`
Make sure you upgrade both your dbt core as well as your adapter

**Comment by hanslemm** [comment]
In my case, after many trials and errors, I discovered that if you reinstall `dbt-core` after `dbt-adapters` is already installed, this error arises. So you actually need to reinstall both with --force-install.

**Comment by jaceksan** [comment]
Hit this issue too when bumping dbt from 1.7.x to 1.9.x because I had to bump dbt-duckdb (MotherDuck deprecates 1.0).
I used Python 3.10 due to historical reasons.
When I bumped Python to 3.12, the problem disappeared.

**Comment by petersjanjaap** [comment]
pip install dbt-fabric fixed it for me, it adds the adapter for fabric. It's unfortunate it is imported into the cli functionality, because it requires you to install dbt-fabric, even though you are using a different db to interact with (say BigQuery).

**Comment by tgmof** [comment]
> In my case, after many trials and errors, I discovered that if you reinstall `dbt-core` after `dbt-adapters` is already installed, this error arises. So you actually need to reinstall both with --force-install.

I can confirm what @hanslemm wrote. We have a CICD pipeline that tries to build / install dependencies using Poetry and it only fails when our pipeline installs dbt-adapters and then tries to upgrade dbt-core. 

Indeed, the pipelines that use a Docker image that already contains dbt-core (but not yet dbt-adapters) do the following:

> Installing dbt-adapters (1.7.0)
> Updating dbt-core (1.7.0 -> 1.8.7)

The pipelines that use an 'empty' Docker image do the following:

> Installing dbt-adapters (1.7.0)
> Installing dbt-core (1.8.7)

I can't confirm 100% that this "installing/updating" order is the root cause of it but at least I observe the same thing as what @hanslemm describes.
I doubt that upgrading to python3.12 solves the issue since this whole issue thread was created by someone who raised the issue for Python3.12 (so my guess is that the people that claim that "upgrading to python 3.12 solved the issue" actually re-installed all dependencies and this re-installation had the consequence of solving the issue, not the Python Version itself).

<details>
<summary>Detail of the poetry traces</summary>
The CICD run that works:

```bash
  • Installing pytz (2024.2)
  • Installing requests (2.32.3)
  • Installing tzdata (2024.2)
  • Installing zipp (3.21.0)
  • Installing click (8.1.7)
  • Installing dbt-common (1.10.0)
  • Installing google-api-core (2.23.0)
  • Installing google-crc32c (1.6.0)
  • Installing grpcio-status (1.62.3)
  • Installing importlib-metadata (6.11.0)
  • Installing more-itertools (10.5.0)
  • Installing packaging (24.2)
  • Installing pandas (2.2.3)
  • Installing pyarrow (18.1.0)
  • Installing pydantic (2.10.2)
  • Installing pyyaml (6.0.2)
  • Installing daff (1.3.46)
  • Installing db-dtypes (1.3.1)
  • Installing dbt-adapters (1.7.0)
  • Installing dbt-extractor (0.5.1)
  • Installing dbt-semantic-interfaces (0.5.1)
  • Installing google-cloud-core (2.4.1)
  • Installing google-resumable-media (2.7.2)
  • Installing grpc-google-iam-v1 (0.13.1)
  • Installing logbook (1.5.3)
  • Installing minimal-snowplow-tracker (0.0.2)
  • Installing networkx (3.4.2)
  • Installing sqlparse (0.5.2)
  • Installing dbt-core (1.8.7)
  • Installing google-cloud-bigquery (3.27.0)
  • Installing google-cloud-dataproc (5.15.1)
  • Installing google-cloud-storage (2.18.2)
  • Installing dbt-bigquery (1.8.2)
  • Downgrading setuptools (69.5.1 -> 68.2.2)
```

The CICD run that fails:

```bash
  • Updating pytz (2024.1 -> 2024.2)
  • Installing tzdata (2024.2)
  • Updating zipp (3.19.2 -> 3.21.0)
  • Installing dbt-common (1.10.0)
  • Updating google-api-core (2.19.1 -> 2.23.0)
  • Updating google-crc32c (1.5.0 -> 1.6.0)
  • Updating grpcio-status (1.62.2 -> 1.62.3)
  • Updating more-itertools (10.3.0 -> 10.5.0)
  • Updating packaging (24.1 -> 24.2)
  • Installing pandas (2.2.3)
  • Installing pyarrow (18.1.0)
  • Updating pydantic (2.8.2 -> 2.10.2)
  • Updating pyyaml (6.0.1 -> 6.0.2)
  • Installing daff (1.3.46)
  • Installing db-dtypes (1.3.1)
  • Installing dbt-adapters (1.7.0)
  • Updating dbt-semantic-interfaces (0.4.4 -> 0.5.1)
  • Updating google-resumable-media (2.7.1 -> 2.7.2)
  • Updating networkx (3.3 -> 3.4.2)
  • Updating sqlparse (0.4.4 -> 0.5.2)
  • Updating dbt-core (1.7.0 -> 1.8.7)
  • Updating google-cloud-bigquery (3.25.0 -> 3.27.0)
  • Updating google-cloud-dataproc (5.10.1 -> 5.15.1)
  • Updating google-cloud-storage (2.18.0 -> 2.18.2)
  • Updating dbt-bigquery (1.7.6 -> 1.8.2)
```
</details>

**Comment by jaceksan** [comment]
> I can't confirm 100% that this "installing/updating" order is the root cause of it but at least I observe the same thing as what [@hanslemm](https://github.com/hanslemm) describes. I doubt that upgrading to python3.12 solves the issue since this whole issue thread was created by someone who raised the issue for Python3.12 (so my guess is that the people that claim that "upgrading to python 3.12 solved the issue" actually re-installed all dependencies and this re-installation had the consequence of solving the issue, not the Python Version itself).

Works for me with this setup.

requirements-dbt.txt:
```
dbt-postgres~=1.9.0
dbt-snowflake~=1.9.0
# Vertica has not been updated to 1.9 yet. The current pipeline does not run on Vertica.
# dbt-vertica==1.7.3
dbt-duckdb~=1.9.1
duckdb~=1.1.3
setuptools==69.5.1
```

packages.yml:
```
packages:
  - package: Snowflake-Labs/dbt_constraints
    version: 0.6.1
  - package: dbt-labs/codegen
    version: 0.10.0
  - package: calogica/dbt_date
    version: 0.9.1
```

Dockefile:
```
ARG PYTHON_VERSION=3.12
ARG DBT_VERSION=1.9.1
ARG DBT_IMAGE=ghcr.io/dbt-labs/dbt-core:$DBT_VERSION
ARG SRC_DATA_PIPELINE=data_pipeline
FROM $DBT_IMAGE

ARG IMAGES_WORKDIR=/project
WORKDIR ${IMAGES_WORKDIR}

ARG SRC_DATA_PIPELINE
COPY ${SRC_DATA_PIPELINE}/requirements-dbt.txt requirements-dbt.txt
RUN pip3 install -r requirements-dbt.txt

COPY ${SRC_DATA_PIPELINE}/packages.yml packages.yml
COPY ${SRC_DATA_PIPELINE}/dbt_project.yml dbt_project.yml

# dbt deps needs profiles.yml, don't know why. TODO: investigate
COPY ${SRC_DATA_PIPELINE}/profile/profiles.yml /root/.dbt/profiles.yml
RUN dbt deps

ENTRYPOINT ["dbt"]
```

**Comment by tgmof** [comment]
> > I can't confirm 100% that this "installing/updating" order is the root cause of it but at least I observe the same thing as what [@hanslemm](https://github.com/hanslemm) describes. I doubt that upgrading to python3.12 solves the issue since this whole issue thread was created by someone who raised the issue for Python3.12 (so my guess is that the people that claim that "upgrading to python 3.12 solved the issue" actually re-installed all dependencies and this re-installation had the consequence of solving the issue, not the Python Version itself).
> 
> Works for me with this setup.

Yes, what I wrote above and tried to explain (but maybe too fuzzily and not clearly enough?) is:
- It works on all fresh install (which looks to be what your Docker file does, a fresh install that includes a req.txt that references dependencies that themselves depend on dbt-adapters).
- It does NOT work for Docker images where dbt-core was pre-installed and we do poetry install (at runtime, not build time) which updates dbt-core after installing dbt-adapters (which is the issue I tried to explain / document in my message above and matches with what @hanslemm mentioned - even though I'm unsure his findings are just correlated to the root cause or ARE the root cause).

**Comment by jaceksan** [comment]
> Yes, what I wrote above and tried to explain (but maybe too fuzzily and not clearly enough?) is:
> 
>     * It works on all fresh install (which looks to be what your Docker file does, a fresh install that includes a req.txt that references dependencies that themselves depend on dbt-adapters).
> 
>     * It does NOT work for Docker images where dbt-core was pre-installed and we do poetry install (at runtime, not build time) which updates dbt-core after installing dbt-adapters (which is the issue I tried to explain / document in my message above and matches with what [@hanslemm](https://github.com/hanslemm) mentioned - even though I'm unsure his findings are just correlated to the root cause or ARE the root cause).

Eh, sorry. I overlooked the context (expand all comments).
Another reason why the immutable approach is so beneficial ;-)

**Comment by pablo-espeso** [comment]
These lines worked for me:

```bash
pip3 install --force-reinstall dbt-duckdb
pip3 install --force-reinstall dbt-core
```

**Comment by brabster** [comment]
Still seems like the explanation I gave in [this May 17, 2024 comment](https://github.com/dbt-labs/dbt-core/issues/10135#issuecomment-2118230255) explains all the issues folks have seen. In a nutshell:

- Prior to the adapters refactor (moving it out of dbt-core) in dbt 1.8, dbt-core "owned" the installed `dbt/adapters` dir in `site_packages`, as far as pip et al. are concerned.
- The refactor to extract dbt-adapters made dbt-adapters "own" that directory instead.
- When pip does an in-place upgrade, it iterates over packages **in alphabetical order by package name**, copying new files into `site_packages` and deleting files that are no longer needed.
- So.... when you try and upgrade from pre-1.8 to post-1.8, pip **FIRST** installs dbt-adapters files into `site_packages/dbt/adapters` **AND THEN** deals with dbt-core **DELETING** files that dbt-adapters put there that have the same names - like `factory.py`

Why do the fixes work?

- When you then run `install dbt-adapters` it's not fixed because pip thinks there's nothing to do.
- `--force-reinstall` makes pip install all packages again, regardless of the package you specify ([docs](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-force-reinstall)), fixing the problem because we no longer have a version currently installed that "owns" files that are now "owned" by dbt-adapters - so it's same as a fresh install.
- reinstalling from scratch works for the same reason - no version of dbt-core that owned those files currently installed

Maybe I missed something - any behaviour seen since not explained by that?

It seems odd and non-default behaviour that these packages files end up in the same site_packages dir. Presumably that's a choice dbt Labs made as part of the refactor - and it appears to have this unfortunate side effect. Perhaps if a future version moved the directory that dbt-adapters lands its files in site_packages, the problem could actually be fixed. If I get a minute I might try a PR to see.

**Comment by fabian-bode** [comment]
> --force-install

it should be --force-reinstall though :)

**Comment by Barten74** [comment]
In my case, I had a DataFrame with a column timestamp of type datetime64[ns]. Since PySpark 3.5, this type is no longer supported, and you need to change it to datetime64[us].

I fixed it with:

`df['timestamp'] = df['timestamp'].astype('datetime64[us]')`

**Comment by orenl91** [comment]
Happend to me now also when tried to upgrade my dbt to 1.8.0

the solution that worked for me was to downgrade the dbt-adapters package from 1.13.2 to 1.13.1

**Comment by kumpirusha** [comment]
I am having the same issue when upgrading `dbt` packages to `1.9.x` inside a docker environment. I am running into this issue even with a clean env install (all packges are installed during Dockerfile buildtime). Regarding what @tgmof said about docker images I have tried to install `dbt` both via Dockerfile and through a manual install from a clean image and the result is always the same. Any help/advice would be welcome.
```bash
[dp-dev@efb69b596dcb dbt-hub]$ pip list | grep dbt
dbt-adapters              1.14.3
dbt-athena                1.9.2
dbt-athena-community      1.9.2
dbt-common                1.16.0
dbt-core                  1.9.3
dbt-duckdb                1.9.2
dbt-extractor             0.5.1
dbt-semantic-interfaces   0.7.4
```
Running `dbt debug` errors out with missing adapter error:
```bash
[dp-dev@efb69b596dcb dbt-hub]$ dbt debug
09:26:13  Running with dbt=1.9.3
09:26:13  dbt version: 1.9.3
09:26:13  python version: 3.11.6
09:26:13  python path: /opt/virtualenv/bin/python3.11
09:26:13  os info: Linux-6.12.5-linuxkit-x86_64-with-glibc2.34
09:26:13  Error importing adapter: No module named 'dbt.adapters.athena'
09:26:13  Using profiles dir at /home/dp-dev/.dbt
09:26:13  Using profiles.yml file at /home/dp-dev/.dbt/profiles.yml
09:26:13  Using dbt_project.yml file at /home/dp-dev/dbt-hub/bts_dbt_hub/dbt_project.yml
09:26:13  Configuration:
09:26:13    profiles.yml file [ERROR invalid]
09:26:13    dbt_project.yml file [OK found and valid]
09:26:13  Required dependencies:
09:26:13   - git [OK found]

09:26:13  Connection test skipped since no profile was found
09:26:13  1 check failed:
09:26:13  Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "dbt_poc", target "dev" invalid: Runtime Error
    Could not find adapter type athena!
```

**Comment by brabster** [comment]
@kumpirusha I think that's an unrelated problem? My guess would be you have multiple adapters installed that all claim the "athena" type. I'm guessing you have an explicit dependency on both `dbt-athena` and `dbt-athena-community`? Try removing `dbt-athena-community` from your dependencies. Confusing, but I think it's effectively deprecated now that dbt Labs has taken ownership of the adapter.

The current instructions say to depend only on `dbt-core` and `dbt-athena` https://docs.getdbt.com/docs/core/connect-data-platform/athena-setup

If that doesn't work maybe share the direct dependencies you have specified to aid reproduction?

**Comment by kumpirusha** [comment]
@brabster thanks for pointing that out. I have removed the deprecated adapter from the dependency list but unfortunately the issue persists. I am sharing my full environment dependency list below:
<details>

<summary>**Package list:**</summary>

```bash
agate==1.9.1
annotated-types==0.7.0
attrs==25.3.0
babel==2.17.0
black==25.1.0
boto3-stubs[athena,glue,lakeformation,sts]==1.37.16
boto3==1.37.16
botocore-stubs==1.37.16
botocore==1.37.16
certifi==2025.1.31
chardet==5.2.0
charset-normalizer==3.4.1
click==8.1.8
colorama==0.4.6
daff==1.3.46
dateparser==1.2.1
dbt-adapters==1.14.3
dbt-athena==1.9.2
dbt-common==1.16.0
dbt-core==1.9.3
dbt-duckdb==1.9.2
dbt-extractor==0.5.1
dbt-semantic-interfaces==0.7.4
decorator==5.2.1
deepdiff==7.0.1
diff-cover==9.2.4
duckdb==1.2.1
execnet==2.1.1
flake8==7.1.2
fsspec==2025.3.0
idna==3.10
importlib-metadata==6.11.0
iniconfig==2.1.0
invoke==2.2.0
isodate==0.6.1
jinja2==3.1.6
jmespath==1.0.1
jsonpath-rw==1.4.0
jsonschema-specifications==2024.10.1
jsonschema==4.23.0
leather==0.4.0
markupsafe==3.0.2
mashumaro[msgpack]==3.14
mccabe==0.7.0
mmh3==4.1.0
more-itertools==10.6.0
msgpack==1.1.0
mypy-boto3-athena==1.37.0
mypy-boto3-glue==1.37.13
mypy-boto3-lakeformation==1.37.13
mypy-boto3-sts==1.37.0
mypy-extensions==1.0.0
networkx==3.4.2
numpy==2.2.4
ordered-set==4.1.0
packaging==24.2
parsedatetime==2.6
pathspec==0.12.1
platformdirs==4.3.7
pluggy==1.5.0
ply==3.11
protobuf==5.29.3
pyathena==3.12.2
pycodestyle==2.12.1
pydantic-core==2.27.2
pydantic==2.10.6
pyflakes==3.2.0
pygments==2.19.1
pytest-xdist==3.6.1
pytest==8.3.5
python-dateutil==2.9.0.post0
python-slugify==8.0.4
pytimeparse==1.1.8
pytz==2025.1
pyyaml==6.0.2
referencing==0.36.2
regex==2024.11.6
requests==2.32.3
rpds-py==0.23.1
s3transfer==0.11.4
six==1.17.0
slack-sdk==3.35.0
snowplow-tracker==1.1.0
sqlfluff==3.3.1
sqlparse==0.5.3
tblib==3.0.0
tenacity==9.0.0
text-unidecode==1.3
tqdm==4.67.1
types-awscrt==0.24.2
types-s3transfer==0.11.4
typing-extensions==4.12.2
tzdata==2025.1
tzlocal==5.3.1
urllib3==2.3.0
yamllint==1.37.0
zipp==3.21.0
```

</details>

**Comment by kumpirusha** [comment]
Got it sorted by locking `dbt-athena` to version `1.9.0`

**Comment by DivyaNayaka** [comment]
When i did upgrade dbt-extractor          was                0.5.1 and it was failing.
when i did fresh install dbt-extractor                          0.6.0

After fresh install everything worked.

**Comment by moseleyi** [comment]
I have to use my old laptop for the moment and this issue came back. Tried to simply upgrade dbt-core and dbt-bigquery and  even installed dbt-core 1.9.6 instead of 1.10.2 and still can't solve the `No module named dbt.adapters.factory` problem..

**Comment by vevetron** [comment]
I pretty much couldn't fix with any of the steps I tried from above.  
dbt-core = "1.8.1" -> "1.10.1"
dbt-bigquery = "1.8.1" -> "1.10.0"
After I updated these packages and did a poetry lock, poetry install, further steps were fine.

**Comment by Bass22** [comment]
Hi guys

In case somebody has the same issue, I just solved it by doing:
pipenv uninstall dbt-core dbt-bigquery sqlfluff
After that, I did:
pipenv install dbt-core==1.8 dbt-bigquery==1.8
And, it is working again.

PS: I switched to dbt 1.7 and had the error when trying to get back to 1.8

**Comment by PoonamKucheriya** [comment]
Verifying dbt installation...
Core:
  - installed: 1.8.8  
  - latest:    1.10.11 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - postgres: 1.8.2 - Update available!
  - redshift: 1.8.1 - Update available!

  **_### At least one plugin is out of date or incompatible with dbt-core._**
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation


what does this mean. There is no way to find anything compatible to dbt-Core: 1.8.8  
Any idea? who is this referring to -  At least one plugin is out of date or incompatible with dbt-core._**

**Comment by graciegoheen** [comment]
> When I got the same error as the reported above, the following workaround resolved it for me:
> 
> python -m pip uninstall -y dbt-adapters
> python -m pip install --upgrade dbt-core dbt-common dbt-adapters
> dbt --version
> The `pip uninstall -y dbt-adapters` is the important part.
> 
> The 2nd command can be replaced with whichever command you use to install the requirements for dbt 1.8.

^I'm going to close this out and recommend that folks use this workaround if still running into this issue.
